version: "3.8"
services:
  server:
    container_name: reddex_v2_server
    image: tyrelchambers/reddex-api
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: unless-stopped
    command: npm start
    depends_on:
      - db
      - mongodb
  db:
    container_name: reddex_v2_db
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  mongodb:
    container_name: mongodb_reddex
    image: mongo
    restart: unless-stopped

networks:
  default:
    name: reddex_v2_backend
volumes:
  postgres_data:
